version: '3'
volumes:
  postgres_data: {}
  cassandra_data: {}
networks:
  pock-multiplayer-network: {}
  dc1ring: {}
services:
  postgres:
    restart: unless-stopped
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pock-multiplayer-network
  # Configuration for our seed cassandra node. The node is call DC1N1
  # .i.e Node 1 in Data center 1.
  DC1N1:
      # Cassandra image for Cassandra version 3.1.0. This is pulled
      # from the docker store.
      image: cassandra:latest
      # Network for the nodes to communicate
      networks:
          - dc1ring
      # Maps cassandra data to a local folder. This preserves data across
      # container restarts. Note a folder n1data get created locally
      volumes:
          - cassandra_data:/var/lib/cassandra/n1data
      # Docker constainer environment variable. We are using the
      # CASSANDRA_CLUSTER_NAME to name the cluster. This needs to be the same
      # across clusters. We are also declaring that DC1N1 is a seed node.
      environment:
          - CASSANDRA_CLUSTER_NAME=dev_cluster
          - CASSANDRA_SEEDS=DC1N1
      # Exposing ports for inter cluste communication
      expose:
          - 7000
          - 7001
          - 7199
          - 9042
          - 9160
      # Cassandra ulimt recommended settings
      ulimits:
          memlock: -1
          nproc: 32768
          nofile: 100000
      ports:
          - "9042:9042"
  # This is configuration for our non seed cassandra node. The node is call
  # DC1N1 .i.e Node 2 in Data center 1.
  DC1N2:
      # Cassandra image for Cassandra version 3.1.0. This is pulled
      # from the docker store.
      image: cassandra:latest
      # Network for the nodes to communicate
      networks:
          - dc1ring
      # Maps cassandra data to a local folder. This preserves data across
      # container restarts. Note a folder n1data get created locally
      volumes:
          - cassandra_data:/var/lib/cassandra/n2data
      # Docker constainer environment variable. We are using the
      # CASSANDRA_CLUSTER_NAME to name the cluster. This needs to be the same
      # across clusters. We are also declaring that DC1N1 is a seed node.
      environment:
          - CASSANDRA_CLUSTER_NAME=dev_cluster
          - CASSANDRA_SEEDS=DC1N1
      # Since DC1N1 is the seed node
      depends_on:
            - DC1N1
      # Exposing ports for inter cluste communication. Note this is already
      # done by the docker file. Just being explict about it.
      expose:
          # Intra-node communication
          - 7000
          # TLS intra-node communication
          - 7001
          # JMX
          - 7199
          # CQL
          - 9042
          # Thrift service
          - 9160
      # Cassandra ulimt recommended settings
      ulimits:
          memlock: -1
          nproc: 32768
          nofile: 100000
      ports:
          - "9043:9042"
  # A web based interface for managing your docker containers.
  portainer:
      image: portainer/portainer
      networks:
          - dc1ring
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - cassandra_data:/var/lib/portainer
      # Enable you to access potainers web interface from your host machine
      # using http://localhost:10001
      ports:
          - "10001:9000"