// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/world.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace World {
  public static partial class World
  {
    static readonly string __ServiceName = "world.World";

    static readonly grpc::Marshaller<global::World.AddRequest> __Marshaller_world_AddRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::World.AddRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::World.AddReply> __Marshaller_world_AddReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::World.AddReply.Parser.ParseFrom);

    static readonly grpc::Method<global::World.AddRequest, global::World.AddReply> __Method_Add = new grpc::Method<global::World.AddRequest, global::World.AddReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Add",
        __Marshaller_world_AddRequest,
        __Marshaller_world_AddReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::World.WorldReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of World</summary>
    [grpc::BindServiceMethod(typeof(World), "BindService")]
    public abstract partial class WorldBase
    {
      public virtual global::System.Threading.Tasks.Task<global::World.AddReply> Add(global::World.AddRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for World</summary>
    public partial class WorldClient : grpc::ClientBase<WorldClient>
    {
      /// <summary>Creates a new client for World</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public WorldClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for World that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public WorldClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected WorldClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected WorldClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::World.AddReply Add(global::World.AddRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Add(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::World.AddReply Add(global::World.AddRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Add, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::World.AddReply> AddAsync(global::World.AddRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::World.AddReply> AddAsync(global::World.AddRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Add, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override WorldClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new WorldClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(WorldBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Add, serviceImpl.Add).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, WorldBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Add, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::World.AddRequest, global::World.AddReply>(serviceImpl.Add));
    }

  }
}
#endregion
