app:
  name: gateway
  version: 1.0.0

http:
  port: 8001

logger:
  level: debug

secrets:
  jwt: xXx_qwerty69_xXx

database:
  host: localhost
  user: postgres
  password: postgres
  dbname: postgres
  port: 5433
  sslmode: disable
  timeZone: Europe/Paris