app:
  name: gateway
  version: 1.0.0

http:
  port: 8001

logger:
  level: debug

secrets:
  jwt: xXx_qwerty69_xXx

database:
  host: localhost
  user: User
  password: postgres
  dbname: dbname
  port: 3500
  sslmode: disable
  timeZone: Europe/Paris